name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: pip
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Build package
      run: make dist
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
